import ClientOnly from './components/ClientOnly'
import Modal from './components/modals/Modal'
import { useState } from "react"
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <ClientOnly>
        <Modal title="Hello World" isOpen />

      </ClientOnly>
      
      </body>
    </html>
  )
}
